@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJnby1qd3QtbWlkZGxld2FyZS1leGFtcGxlIiwiZXhwIjoxNjc4ODkzMTI3LCJpYXQiOjE2Nzg4OTMwNjcsImlzcyI6ImdvLWp3dC1taWRkbGV3YXJlLWV4YW1wbGUiLCJuYW1lIjoiYWRtaW4iLCJzdWIiOiJmb3J0ZXN0In0.aYnPnfNiiH7xK8ZN54a0_QLWpbga3lqKbial3rUiR-Y
###

POST http://localhost:18080/v1/login
content-type: application/json

{
    "name": "admin",
    "password": "test01"
}

###

GET http://localhost:18080/v1/users
Authorization: {{token}}

###
GET http://localhost:18080/v1/secure
Authorization: {{token}}

###
POST http://localhost:18080/v1/orders
Authorization: {{token}}
content-type: application/json

{
    "user_id": 201,
    "price": 4294967295,
    "contained": true
}

###

POST http://localhost:18080/v1/orders/shipping_fee
Authorization: {{token}}
content-type: application/json

{
    "size": "small",
    "option": "regular",
    "region": "hokkado"
}